query GetAppSettings {
  getAppSettings {
    userCredentialKey
    userCredentialPassword
    parentCredentialKey
    parentCredentialPassword
    clientDetailAccountNumber
    clientDetailMeterNumber
    isLive
    residential
    optimizeShippingType
    unitWeight
    unitDimension
    itemModals {
      modal
      fedexHandling
      shipAlone
    }
    slaSettings {
      sla
      hidden
      surchargeFlatRate
      surchargePercent
    }
  }
}
