query GetAppSettings {
  getAppSettings {
    userCredentialKey
    userCredentialPassword
    parentCredentialKey
    parentCredentialPassword
    clientDetailAccountNumber
    clientDetailMeterNumber
    isLive
    optimizeShipping
    unitWeight
    unitDimension
    hiddenSLA
    itemModals {
      modal
      fedexHandling
      shipAlone
    }
  }
}
